# Generated by Django 3.0.2 on 2020-08-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_auto_20200803_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='animals'),
        ),
    ]
